### ISSUE TITLE
Soren should have less of a white halo around his face

### ISSUE THREAD

**Issue by jesperrasmussen** [kennethlarsen/Sessionslogning-simulator#1]
Unless it's on purpose, to show his aura of innocence :smirk:

**Comment by kennethlarsen** [comment]
I have horrible graphic skills. GIMP didn't have a "remove aura of innocence" feature :(

**Comment by Znegl** [comment]
Fixet here: https://github.com/kennethlarsen/Sessionslogning-simulator/pull/2

**Comment by kennethlarsen** [comment]
Thanks!
